/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frameSam;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Chell
 */
public class fAddGuards extends javax.swing.JFrame {

    /**
     * Creates new form fAddGuards
     */
    public fAddGuards() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guardsG = new javax.swing.ButtonGroup();
        GDone = new javax.swing.JButton();
        gGetName = new javax.swing.JTextField();
        gName = new javax.swing.JLabel();
        gClear = new javax.swing.JButton();
        gBack = new javax.swing.JButton();
        gAge = new javax.swing.JLabel();
        gGetAge = new javax.swing.JTextField();
        YoSer = new javax.swing.JLabel();
        inMale = new javax.swing.JRadioButton();
        inFemale = new javax.swing.JRadioButton();
        gYear = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GDone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GDone.setText("DONE");
        GDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GDoneActionPerformed(evt);
            }
        });

        gGetName.setText("Enter The Name");
        gGetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gGetNameActionPerformed(evt);
            }
        });

        gName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gName.setText("NAME");

        gClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gClear.setText("CLEAR");
        gClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gClearActionPerformed(evt);
            }
        });

        gBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gBack.setText("BACK");
        gBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gBackActionPerformed(evt);
            }
        });

        gAge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gAge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gAge.setText("AGE");

        gGetAge.setText("Enter Age Of The Guard");
        gGetAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gGetAgeActionPerformed(evt);
            }
        });

        YoSer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        YoSer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YoSer.setText("Year's Of Service");

        guardsG.add(inMale);
        inMale.setText("Male");
        inMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inMaleActionPerformed(evt);
            }
        });

        guardsG.add(inFemale);
        inFemale.setText("Female");

        gYear.setText("Enter Years");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(gName, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(gAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(YoSer)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gGetName)
                            .addComponent(gGetAge, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(gYear)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(GDone, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gClear, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gBack, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(inMale)
                .addGap(49, 49, 49)
                .addComponent(inFemale)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gGetName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gClear)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gGetAge, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(gAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gBack)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(YoSer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inMale)
                            .addComponent(inFemale))
                        .addGap(45, 45, 45)
                        .addComponent(GDone, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GDoneActionPerformed
        try
        {
            String name = gGetName.getText();
       
            int age = Integer.parseInt(gGetAge.getText());
            int year = Integer.parseInt(gYear.getText());
            Date d = new Date(0 , 0 , 0);
            String gender;
            if(inMale.isSelected() && !inFemale.isSelected())
                gender = "Male";
            else
                gender = "Female";
         
           
            Login.g = new Guards(name , age , gender,year , d);
            Login.guard.addGuard(Login.g);
            //outIdNo.setText(String.valueOf(Login.p.uniqueiD));
       
            
            gGetName.setText("");
            gGetAge.setText("");
            gYear.setText("");
            
            
            JOptionPane.showMessageDialog(this,"THE GUARD CODE IS: "+Login.g.guardCode,"Success",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this,"INVALID INPUT ","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_GDoneActionPerformed

    private void gGetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gGetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gGetNameActionPerformed

    private void gClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gClearActionPerformed
        gGetName.setText("");
        gGetAge.setText("");
        gYear.setText("");
        

    }//GEN-LAST:event_gClearActionPerformed

    private void gGetAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gGetAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gGetAgeActionPerformed

    private void gBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new fGuards().setVisible(true);
    }//GEN-LAST:event_gBackActionPerformed

    private void inMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inMaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fAddGuards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fAddGuards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fAddGuards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fAddGuards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fAddGuards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GDone;
    private javax.swing.JLabel YoSer;
    private javax.swing.JLabel gAge;
    private javax.swing.JButton gBack;
    private javax.swing.JButton gClear;
    private javax.swing.JTextField gGetAge;
    private javax.swing.JTextField gGetName;
    private javax.swing.JLabel gName;
    private javax.swing.JTextField gYear;
    private javax.swing.ButtonGroup guardsG;
    private javax.swing.JRadioButton inFemale;
    private javax.swing.JRadioButton inMale;
    // End of variables declaration//GEN-END:variables
}
