/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frameSam;

/**
 *
 * @author Nehal Kalnad
 */
public class Login extends javax.swing.JFrame {
    
    public static Prison maleP = new Prison(0 );//Male Prisoners      
    public static Prison guard =new Prison(11);//Guard
    public static Prisoner p; //Our Jail can hold 10 Prisoners
    public static Guards g; //Only 5 Guards
    public Services s = new Services();
    public int pC = 0 , gC = 0;
    public Prisoner temp;
    public int tempC;
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Date dd = new Date(6,7 ,1988);
        p = new Prisoner("Nehal" , 19 , "Male" , dd);
        maleP.addPrisoner(p);
        p = new Prisoner("Kartick" , 21 , "Male" , dd);
        maleP.addPrisoner(p);
        p = new Prisoner("Ashley" , 24 , "Male" , dd);
        maleP.addPrisoner(p);
        dd = new Date(9,12,1972);
        g = new Guards("Ram Singh" , 42 , "Male" , 9 , dd);
        guard.addGuard(g);
        g = new Guards("Lakhan" , 32 , "Male" , 5 , dd);
        guard.addGuard(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iUsername = new javax.swing.JTextField();
        iPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iUsername.setText("Username");
        iUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iUsernameMouseClicked(evt);
            }
        });
        iUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(iUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 140, 30));

        iPassword.setText("jPasswordField1");
        iPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iPasswordMouseClicked(evt);
            }
        });
        iPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(iPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 140, 30));

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frameSam/jail-clipart-7.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HomeFrame().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void iUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iUsernameMouseClicked
           // TODO add your handling code here:
           iUsername.setText("");
    }//GEN-LAST:event_iUsernameMouseClicked

    private void iUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iUsernameActionPerformed

    private void iPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iPasswordActionPerformed

    private void iPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iPasswordMouseClicked
        // TODO add your handling code here:
        iPassword.setText("");
    }//GEN-LAST:event_iPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField iPassword;
    private javax.swing.JTextField iUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
